#!/bin/bash

# Packages management
alias clean="sudo apt-fast autoremove; sudo apt-fast autoclean; sudo apt-fast purge; sudo apt-fast clean"
alias update="sudo apt-fast update --quiet; sudo apt-fast upgrade --yes"
alias unlockdpkg="sudo fuser -vik /var/lib/dpkg/lock; sudo dpkg --configure -a"
alias cleanpackages="sudo dpkg --get-selections | grep deinstall | sed 's/\t\+.*//g' | xargs sudo dpkg --purge"

# Vim (Gvim)
alias gvim="gvim --remote-silent"
alias eg="gvim .git/config"

# Ruby
alias uninstallgems="gem list | cut -d' ' -f1 | xargs gem uninstall -aIx"

# Helper Functions
function untar () {
    7z e $1
}

function authme {
    ssh $1 '[ ! -e ~/.ssh/ ] && mkdir ~/.ssh 2>/dev/null; cat >>.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
}

function take () {
    mkdir $1
    cd $1
}

function install-macfonts {
    wget https://www.dropbox.com/s/k5n96eelnt9z83u/macfonts.tar.gz
    tar zxvf macfonts.tar.gz && sudo cp -r macfonts/ /usr/share/fonts/
    rm -fr macfonts*
}
