#!/bin/bash

function untar () {
  7z e $1
}

function authme {
  ssh $1 'cat >>.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
}

function ps1 {
  export PS1="\n\[\033[37m\]\u\[\033[32m\]:\w \$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\\033[36m(\1)/' | sed -e 's/(production)/\\033[1;37m\\033[41m(production)\\031[m/' | sed -e 's/(master)/\\033[1;37m\\033[41m(master)\\033[m/' | sed -e 's/(stage)/\\033[31m(stage)/' | sed -e 's/(next)/\\033[33m(next)/')\[\033[37m\]\[\033[0m\] \n∫ "
}

function take () {
  mkdir $1
  cd $1
}

function install-vim () {
  sudo apt-fast install exuberant-ctags ncurses-term vim-gtk ack --yes
	git clone git://github.com/akitaonrails/vimfiles.git ~/.vim
	cd ~/.vim ; git submodule update --init
	if [ ! -e ~/.vimrc ]; then
    echo “source ~/.vim/vimrc” > ~/.vimrc
	fi
}

function backup-packages () {
  if [ ! -d ~/Dropbox/ubuntu-backup ]; then
    mkdir -p ~/Dropbox/ubuntu-backup/
    echo 'Directory to back up was created...'
  fi

  if [ ! -d ~/Dropbox/ubuntu-backup/sources.list.d ]; then
    mkdir -p ~/Dropbox/ubuntu-backup/sources.list.d/
    echo 'Directory to back up third part sources list was created...'
  fi

  dpkg --get-selections > ~/Dropbox/ubuntu-backup/backup_packages.txt
  echo 'All the packages installed were backed up...'

  cp /etc/apt/sources.list ~/Dropbox/ubuntu-backup/
  echo 'Sources list also backed up...'

  cp /etc/apt/sources.list.d/* ~/Dropbox/ubuntu-backup/sources.list.d/
  echo 'Third part sources list backed up...'

  echo 'Done!'
}

function install-rvm {
  sudo apt-fast update && sudo apt-fast install build-essential git-core curl --yes
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc
  source ~/.bashrc
}

function install-essential-packages {
  sudo apt-fast install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion --yes
}

